name: main

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16

      - uses: bahmutov/npm-install@v1

      - run: yarn type
      - run: yarn lint
      # - run: yarn test
      - run: yarn build
      - run: yarn surge ./build march-platane.surge.sh
        env:
          SURGE_TOKEN: ${{ secrets.SURGE_TOKEN }}
          SURGE_LOGIN: ${{ secrets.SURGE_LOGIN }}
